# Generated by Django 5.0.2 on 2024-03-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_cake_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='parent',
        ),
    ]
