# Generated by Django 5.0.2 on 2024-03-04 18:49

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_remove_cake_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cakes.cake'),
        ),
    ]
